name = "sambreed-dev"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-05-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"

[env.production]
compatibility_date = "2025-05-25"
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_date = "2025-05-25"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
